// Constants and Initial Data for Phonics Kingdom
import { SkillNode, SkillLevel } from './types';

export const INITIAL_NODES: SkillNode[] = [
  // Phonemic Awareness
  {
    id: 'pa-1',
    title: 'Beginning Sounds',
    description: 'Identify the first sound in words',
    level: SkillLevel.PHONEMIC_AWARENESS,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: false,
    attempts: 0,
    timeSpent: 0,
  },
  {
    id: 'pa-2',
    title: 'Ending Sounds',
    description: 'Identify the last sound in words',
    level: SkillLevel.PHONEMIC_AWARENESS,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: true,
    attempts: 0,
    timeSpent: 0,
  },
  {
    id: 'pa-3',
    title: 'Rhyming Words',
    description: 'Match words that rhyme',
    level: SkillLevel.PHONEMIC_AWARENESS,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: true,
    attempts: 0,
    timeSpent: 0,
  },

  // Letter Sounds
  {
    id: 'ls-1',
    title: 'Consonant Sounds',
    description: 'Learn the sounds of consonant letters',
    level: SkillLevel.LETTER_SOUNDS,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: true,
    attempts: 0,
    timeSpent: 0,
  },
  {
    id: 'ls-2',
    title: 'Short Vowel Sounds',
    description: 'Learn short vowel sounds: a, e, i, o, u',
    level: SkillLevel.LETTER_SOUNDS,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: true,
    attempts: 0,
    timeSpent: 0,
  },
  {
    id: 'ls-3',
    title: 'Long Vowel Sounds',
    description: 'Learn long vowel sounds with silent e',
    level: SkillLevel.LETTER_SOUNDS,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: true,
    attempts: 0,
    timeSpent: 0,
  },

  // Digraphs & Blends
  {
    id: 'db-1',
    title: 'Beginning Blends',
    description: 'Learn bl, br, cl, cr, dr, fl, fr, gl, gr',
    level: SkillLevel.DIGRAPHS_BLENDS,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: true,
    attempts: 0,
    timeSpent: 0,
  },
  {
    id: 'db-2',
    title: 'Ending Blends',
    description: 'Learn nd, ng, nk, nt, mp, sk, st',
    level: SkillLevel.DIGRAPHS_BLENDS,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: true,
    attempts: 0,
    timeSpent: 0,
  },
  {
    id: 'db-3',
    title: 'Consonant Digraphs',
    description: 'Learn ch, sh, th, wh, ph',
    level: SkillLevel.DIGRAPHS_BLENDS,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: true,
    attempts: 0,
    timeSpent: 0,
  },

  // Blending CVC
  {
    id: 'cvc-1',
    title: 'CVC Words with A',
    description: 'Read words like cat, bat, hat',
    level: SkillLevel.BLENDING_CVC,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: true,
    attempts: 0,
    timeSpent: 0,
  },
  {
    id: 'cvc-2',
    title: 'CVC Words with E & I',
    description: 'Read words like pet, sit, big',
    level: SkillLevel.BLENDING_CVC,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: true,
    attempts: 0,
    timeSpent: 0,
  },
  {
    id: 'cvc-3',
    title: 'CVC Words with O & U',
    description: 'Read words like hot, cup, run',
    level: SkillLevel.BLENDING_CVC,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: true,
    attempts: 0,
    timeSpent: 0,
  },

  // Sight Words
  {
    id: 'sw-1',
    title: 'Sight Words Set 1',
    description: 'Learn: the, and, is, it, you',
    level: SkillLevel.SIGHT_WORDS,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: true,
    attempts: 0,
    timeSpent: 0,
  },
  {
    id: 'sw-2',
    title: 'Sight Words Set 2',
    description: 'Learn: he, she, we, they, was',
    level: SkillLevel.SIGHT_WORDS,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: true,
    attempts: 0,
    timeSpent: 0,
  },
  {
    id: 'sw-3',
    title: 'Sight Words Set 3',
    description: 'Learn: have, are, said, what, there',
    level: SkillLevel.SIGHT_WORDS,
    accuracy: 0,
    successivePasses: 0,
    isMastered: false,
    isLocked: true,
    attempts: 0,
    timeSpent: 0,
  },
];

export const LEVEL_NAMES: Record<SkillLevel, string> = {
  [SkillLevel.PHONEMIC_AWARENESS]: 'Phonemic Awareness',
  [SkillLevel.LETTER_SOUNDS]: 'Letter Sounds',
  [SkillLevel.DIGRAPHS_BLENDS]: 'Digraphs & Blends',
  [SkillLevel.BLENDING_CVC]: 'Blending CVC',
  [SkillLevel.SIGHT_WORDS]: 'Sight Words',
};

export const CHARACTER_GREETINGS = {
  BRIO: ["Yo! Let's crush it!", "Ready to rock?", "You've got this!"],
  VOWELIA: ["Hello, dear learner...", "Let wisdom guide you", "Breathe and begin..."],
  DIESEL: ["Hey buddy!", "Let's dig in!", "Adventure awaits!"],
  ZIPPY: ["Zoom zoom!", "Let's gooo!", "Ready, set, READ!"],
};
